### ISSUE TITLE
chinese复现失败，差5个点以上

### ISSUE THREAD

**Issue by siftxxx** [mazzzystar/TurtleBenchmark#1]
hi，我用自己的模型调用方式本地复现了一下中文上的评估任务
commit：de0b0fc3686872d04096f63daea5a66e2caecbf9

2-shots
DeepSeek-V2-api：71.37
GPT4o-0513：76.19
看起来差超过5个点。

下面是我的输入格式：
[{\"role\": \"system\", \"content\": \"你是一个游戏的裁判，这个游戏会给玩家展示<汤面>，并告诉你<汤底>，你需要根据<汤面>和<汤底>理解整个故事。玩家会根据<汤面>进行猜测，你需要判断玩家的猜测是否正确，请严格遵守你只回答指定三种答案：对、错、不知道。\\n\\n## 判定规则\\n - 玩家提出的猜测正确，或者答案是肯定的：请只回答\\\"对\\\"，不要做任何解释。\\n - 玩家提出的猜测错误，或者答案是否定的：请只回答\\\"错\\\"，不要做任何解释。\\n - 玩家提出的猜测，从<汤面>和<汤底>找不到答案，并且也无法通过推理得出此结论：请只回答\\\"不知道\\\"，不要做任何解释。\\n\\n## 注意\\n- 请充分理解整个故事的起因、经过和结局，并进行合乎逻辑的推断，如果无法从提供的故事中得出的结论，你应该回答\\\"不知道\\\"，例如：玩家提出的猜测是关于故事中的细节，而这些细节并没有在故事中提到，也无法通过推理得出此结论，那么你应该回答\\\"不知道\\\"。\\n- 严格遵守只回答指定三种答案：对、错、不知道。\\n\\n## 示例\\n\\n### 示例1：打嗝男子\\n<汤面>\\n一个男人走进一家酒吧，并向酒保要了一杯水。酒保却突然拿出一把手枪瞄准他，而男子竟只是笑著说：“谢谢你！”然后从容离开，请问发生了什么事？\\n\\n<汤底>\\n男子打嗝，他希望喝一杯水来改善状况。酒保意识到这一点，选择拿枪吓他，男子一紧张之下，打嗝自然消失，因而衷心感谢酒保后就离开了。\\n\\n可能的猜测及对应的回答：\\n问：男人有慢性病吗？ 答：不知道\\n问：男人是被吓跑了吗 答：错\\n问：酒保想杀死男人 答：错\\n问：酒保是为了吓唬男人 答：对\\n问：男子衷心感谢酒保 答：对\\n\\n### 示例2：四岁的妈妈\\n<汤面>\\n幼儿园五岁的小朋友，竟然说她的妈妈只有四岁，我很疑惑，便提出了去她家家访，随后我在她家看到了让我惊恐的一幕...\\n\\n<汤底>\\n我在她家看到了一个个被铁链拴着的女人，而一旁站着一个长相凶狠丑陋的彪形大汉。幼儿园的那个小朋友突然露出了不属于她这个年龄该有的诡笑...原来她是二十五岁，只是从小得了一种长不大的病，而那个彪形大汉则是她的哥哥，她是为了给她哥哥找女人，便哄骗我们这些幼师来到家里进行迫害…而她那\\\\\\\"四岁的妈妈\\\\\\\"，是已经被骗来四年的女人…\\n\\n可能的猜测及对应的回答：\\n问：小朋友已经死了 答：错\\n问：小朋友其实是成年人 答：对\\n问：小朋友有精神分裂 答：不知道\\n问：我会有危险 答：对\\n\\n\\n现在开始主持:\\n\\n## 题目内容\\n### 汤面\\n托马斯第一次和老婆去老婆闺蜜家，结果回来老婆就要和他离婚了，请问为什么？\\n\\n### 汤底\\n托马斯老婆看见老公的手机自动连上了闺蜜家的WiFi。\\n\\n现在，请判断以下玩家猜测：\"}, {\"role\": \"user\", \"content\": \"闺蜜和老公有一腿\"}]

想知道可能是哪里出问题了～

**Comment by mazzzystar** [comment]
Hi, 我在代码里附上了我们自己测试的json数据：https://github.com/mazzzystar/TurtleBenchmark/blob/main/evaluation/chinese/data/results_2shot.json

你看看有没有办法对比具体哪些case模型的判断和我们的日志不一样呢？

**Comment by siftxxx** [comment]
> Hi, 我在代码里附上了我们自己测试的json数据：https://github.com/mazzzystar/TurtleBenchmark/blob/main/evaluation/chinese/data/results_2shot.json
> 
> 你看看有没有办法对比具体哪些case模型的判断和我们的日志不一样呢？

我读取了[results_2shot.json](https://github.com/mazzzystar/TurtleBenchmark/blob/main/evaluation/chinese/data/results_2shot.json)里的日志，根据手动算了一下分，结果是这样的，跟report的不一样
![image](https://github.com/user-attachments/assets/0a891b85-a925-43c7-b745-022ae0eca74b)

直接算的得分：
```python
import json
import sys
from collections import Counter

n_correct, n_total = 0,0
counter = Counter()
with open(sys.argv[1]) as fin:
    json_data = json.load(fin)
    for item in json_data:
        gt = item['ground_truth']
        for model, pred in item['results'].items():
            if gt == pred:
                counter[model] += 1
        n_total += 1
for model, n_correct in counter.items():
    print(model,  n_correct, n_total, n_correct/n_total)
```

**Comment by siftxxx** [comment]
```注意：我们在标注和计算准确率时将错(F)和不相关(N)进行了合并、不做区分。```
抱歉我没有注意把这两个合并

**Comment by mazzzystar** [comment]
OK，建议你可以先看看我们的统计方法 : ). 另外，因为我们标注时发现有很多N和F都可以的input，所以在某一时刻之后，为了图方便就不做区分了，这导致现有标注里，N和F的标注并不是非常准确(也就是我们不区分二者)。

合并其实会让任务简单，所以我们计划(如果有精力)重新标注以区分N和F，对某些case可以标注为"NF"，也就是既可以N也可以F，这样会让任务更难一些。
